# Generated by Django 3.1.4 on 2021-09-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incomings',
            new_name='Incoming',
        ),
        migrations.RenameModel(
            old_name='PaymentMethods',
            new_name='PaymentMethod',
        ),
    ]
