# Generated by Django 3.1.4 on 2021-09-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Debits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('place', models.TextField(blank=True, default='', null=True)),
                ('nfe', models.CharField(blank=True, default='', max_length=44, null=True)),
                ('type', models.ManyToManyField(to='saida.Category')),
            ],
        ),
    ]
