# Generated by Django 3.1.4 on 2021-09-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='debits',
            name='place',
        ),
        migrations.AddField(
            model_name='debits',
            name='place',
            field=models.ManyToManyField(blank=True, to='saida.Place'),
        ),
    ]
