# Generated by Django 3.1.4 on 2021-09-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saida', '0002_auto_20210922_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debits',
            new_name='Debit',
        ),
    ]
